baseURL = 'https://theproofcentre.github.io/website/'
locale = 'en-US'
title = 'PROOF Centre - Prevention of Organ Failure Centre of Excellence'

ignoreLogs = ['warning-goldmark-raw-html']
disableKinds = ['taxonomy', 'term']

[params]
  description = "Discovery, development, and deployment of non-invasive blood-based biomarker tests for organ failure."
  contact_email = "proof@hli.ubc.ca"

[params.google_sheets]
  enabled = true
  sheet_id = "1WabgRo9nsUT75jzaVqyDrfWLEXBrzX8CYhdTB2cT4o8"
  publications_tab = "Publications"
  team_tab = "Team"
  patents_tab = "Patents"

[menus]
  [[menus.main]]
    name = "Research"
    url = "#focus-areas"
    weight = 10
  [[menus.main]]
    name = "Team"
    url = "#research-team"
    weight = 20
  [[menus.main]]
    name = "Publications"
    url = "#publications"
    weight = 30
  [[menus.main]]
    name = "Patents"
    url = "#patents"
    weight = 40
